%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                   Illustrating Simulation 9-4:               %
%                     Shift Keying Modulations                 %
%                                                              %
%        Book : Analog & Digital Communication Systems         %
%                   By: Dr.Farnaz Ghassemi                     %
%                     Chapter 9-Section                        %
%                                                              %
%   Standalone version: does NOT require Sim_9_4.fig%          %
%   Version.1:             04/03/03---Dr.Ghassemi              %
%   Version.2:             05/05/17---Dr.Ghassemi              %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function varargout = Sim_9_4(varargin)

% This GUI was originally generated by GUIDE and therefore depended on a
% separate Sim_9_4.fig file.  This standalone version creates
% all graphical objects programmatically, so the .m file is sufficient.

% Behave as a singleton: if the GUI is already open, bring it to front.
oldFig = findall(0,'Type','figure','Tag','figure1');
if ~isempty(oldFig) && isgraphics(oldFig(1))
    figure(oldFig(1));
    if nargout > 0
        varargout{1} = oldFig(1);
    end
    return
end

fig = figure('Name','Shift Keying Modulations', ...
    'NumberTitle','off', ...
    'MenuBar','none', ...
    'ToolBar','figure', ...
    'Tag','figure1', ...
    'Units','normalized', ...
    'Position',[0.12 0.10 0.76 0.78], ...
    'Color',get(0,'defaultUicontrolBackgroundColor'), ...
    'Resize','on', ...
    'Visible','off');

handles = struct();
handles.figure1 = fig;

% ---- Bit entry controls -------------------------------------------------
uicontrol('Parent',fig,'Style','text','Units','normalized', ...
    'Position',[0.035 0.925 0.10 0.035], ...
    'String','Input bits:', ...
    'HorizontalAlignment','left', ...
    'FontWeight','bold');

x0 = 0.13;
dx = 0.049;
for k = 1:10
    uicontrol('Parent',fig,'Style','text','Units','normalized', ...
        'Position',[x0+(k-1)*dx 0.955 0.035 0.025], ...
        'String',num2str(k), ...
        'HorizontalAlignment','center');
    hEdit = uicontrol('Parent',fig,'Style','edit','Units','normalized', ...
        'Position',[x0+(k-1)*dx 0.915 0.038 0.045], ...
        'String','0', ...
        'BackgroundColor','white', ...
        'HorizontalAlignment','center', ...
        'FontSize',10, ...
        'Tag',sprintf('bit%d',k));
    handles.(sprintf('bit%d',k)) = hEdit;
end

% ---- Modulation selector and random-bit button --------------------------
uicontrol('Parent',fig,'Style','text','Units','normalized', ...
    'Position',[0.635 0.945 0.12 0.028], ...
    'String','Modulation:', ...
    'HorizontalAlignment','left', ...
    'FontWeight','bold');

handles.select_mod = uicontrol('Parent',fig,'Style','popupmenu', ...
    'Units','normalized', ...
    'Position',[0.735 0.93 0.115 0.045], ...
    'String',{'ASK','OOK','BPSK','QPSK','8PSK','BFSK'}, ...
    'Value',1, ...
    'BackgroundColor','white', ...
    'Tag','select_mod', ...
    'Callback',@(src,event)select_mod_Callback(src,event,guidata(src)));

handles.random = uicontrol('Parent',fig,'Style','pushbutton', ...
    'Units','normalized', ...
    'Position',[0.865 0.93 0.105 0.045], ...
    'String','Random bits', ...
    'FontWeight','bold', ...
    'Tag','random', ...
    'Callback',@(src,event)random_Callback(src,event,guidata(src)));

% ---- Axes ---------------------------------------------------------------
handles.axes1 = axes('Parent',fig,'Units','normalized', ...
    'Position',[0.075 0.57 0.87 0.285], ...
    'Tag','axes1');
title(handles.axes1,'Binary data');
xlabel(handles.axes1,'Sample');
ylabel(handles.axes1,'Amplitude');

handles.axes3 = axes('Parent',fig,'Units','normalized', ...
    'Position',[0.075 0.12 0.87 0.315], ...
    'Tag','axes3');
title(handles.axes3,'Modulated signal');
xlabel(handles.axes3,'Time / sample');
ylabel(handles.axes3,'Amplitude');

% Store handles before OpeningFcn uses them.
guidata(fig,handles);

% Initialize default bits and plots using the original initialization code.
Sim_9_4_OpeningFcn(fig,[],handles,varargin{:});

set(fig,'Visible','on');

if nargout > 0
    varargout{1} = fig;
end


% --- Executes just before Sim_9_4 is made visible.
function Sim_9_4_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to Sim_9_4 (see VARARGIN)
        hold off;
        axes(handles.axes1);
        h=[1 1 0 1 0 0 1 1 1 0];

        % Initialize the bit vector and edit boxes so callbacks never read
        % empty strings (which would become NaN with STR2DOUBLE).
        handles.bits = h;
        set(handles.bit1, 'String', num2str(h(1)));
        set(handles.bit2, 'String', num2str(h(2)));
        set(handles.bit3, 'String', num2str(h(3)));
        set(handles.bit4, 'String', num2str(h(4)));
        set(handles.bit5, 'String', num2str(h(5)));
        set(handles.bit6, 'String', num2str(h(6)));
        set(handles.bit7, 'String', num2str(h(7)));
        set(handles.bit8, 'String', num2str(h(8)));
        set(handles.bit9, 'String', num2str(h(9)));
        set(handles.bit10,'String', num2str(h(10)));

        hold off;
        bit=[];
        for n=1:2:length(h)-1;
            if h(n)==0 & h(n+1)==1
                se=[zeros(1,50) ones(1,50)];
            elseif h(n)==0 & h(n+1)==0
                se=[zeros(1,50) zeros(1,50)];
            elseif h(n)==1 & h(n+1)==0
                se=[ones(1,50) zeros(1,50)];
            elseif h(n)==1 & h(n+1)==1
                se=[ones(1,50) ones(1,50)];
            end
            bit=[bit se];
        end
        plot(bit,'LineWidth',1.5);grid on;
        axis([0 500 -1.5 1.5]);
%*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
        axes(handles.axes3)
        hold off;
        fc=30;
        g=[1 1 0 1 0 0 1 1 1 0]; %modulante
        n=1;
    while n<=length(g)
        if g(n)==0
            tx=(n-1)*0.1:0.1/100:n*0.1;
            p=(1)*sin(2*pi*fc*tx);
            plot(tx,p,'LineWidth',1.5);grid on;
            hold on;
        else 
            tx=(n-1)*0.1:0.1/100:n*0.1;
            p=(2)*sin(2*pi*fc*tx);
            plot(tx,p,'LineWidth',1.5);grid on;
            hold on;
        end
            n=n+1;
            
    end

% Choose default command line output for Sim_9_4
handles.output = hObject;

% Update handles structure
guidata(hObject, handles);

% UIWAIT makes Sim_9_4 wait for user response (see UIRESUME)
% uiwait(handles.figure1);


% --- Outputs from this function are returned to the command line.
function varargout = Sim_9_4_OutputFcn(hObject, eventdata, handles) 
% varargout  cell array for returning output args (see VARARGOUT);
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Get default command line output from handles structure
varargout{1} = handles.output;

% --- Executes on button press in random.
function random_Callback(hObject, eventdata, handles)
% hObject    handle to random (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
a=round(rand(1,10)); %genarar bits aleatorios
ran=[a(1),a(2),a(3),a(4),a(5),a(6),a(7),a(8),a(9),a(10)];
set(handles.bit1,'String',num2str(ran(1)));
set(handles.bit2,'String',num2str(ran(2)));
set(handles.bit3,'String',num2str(ran(3)));
set(handles.bit4,'String',num2str(ran(4)));
set(handles.bit5,'String',num2str(ran(5)));
set(handles.bit6,'String',num2str(ran(6)));
set(handles.bit7,'String',num2str(ran(7)));
set(handles.bit8,'String',num2str(ran(8)));
set(handles.bit9,'String',num2str(ran(9)));
set(handles.bit10,'String',num2str(ran(10)));

%*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
handles.bits=ran;

h=handles.bits;
axes(handles.axes1)
hold off;
bit=[];
for n=1:2:length(h)-1;
    if h(n)==0 & h(n+1)==1
        se=[zeros(1,50) ones(1,50)];
    elseif h(n)==0 & h(n+1)==0
        se=[zeros(1,50) zeros(1,50)];
    elseif h(n)==1 & h(n+1)==0
        se=[ones(1,50) zeros(1,50)];
    elseif h(n)==1 & h(n+1)==1
        se=[ones(1,50) ones(1,50)];
    end
   
    bit=[bit se];
end
plot(bit,'LineWidth',1.5);grid on;
axis([0 500 -1.5 1.5]);

%*-*-*-*-*-*-*-*-*-*-*-*-
hold off;
axes(handles.axes3);
cod=get(handles.select_mod,'Value');
switch cod
%*-*-*-*Modulation ASK*-*-*-*-*-*-*-*-*
    case 1
        hold off;
        axes(handles.axes3)
        fc=30;
        g=handles.bits; %modulante
        n=1;
    while n<=length(g)
        if g(n)==0
            tx=(n-1)*0.1:0.1/100:n*0.1;
            p=(1)*sin(2*pi*fc*tx);
            plot(tx,p,'LineWidth',1.5);grid on;
            hold on;
%    axis([0 n*2/fc -3 3]);
        else 
            tx=(n-1)*0.1:0.1/100:n*0.1;
            p=(2)*sin(2*pi*fc*tx);
            plot(tx,p,'LineWidth',1.5);grid on;
            hold on;
        end
            n=n+1;
    end
    
%*-*-*-*-*-*-*-Modulation OOK*-*-*-*-*-*-*-*-*-
    case 2
        hold off;
        axes(handles.axes3);
        t=0:0.001:1;
        m=1;
        fc=30;
        g=handles.bits; %modulante
        n=1;
        while n<=length(g)
            tx=(n-1)*1/length(g):0.001:n*1/length(g);
            p=(g(n))*sin(2*pi*fc*tx);
            plot(tx,p,'LineWidth',1.5);
            hold on;
            axis([0 (n)*1/length(g) -1.5 1.5]);
            grid on;
            n=n+1;
        end
%*-*-*-*-*-*-*-Modulation BPSK*-*-*-*-*-*-*-*-*-*-*-
    case 3
        axes(handles.axes3)
        hold off;
        g=handles.bits;
        fc=10;
        n=1;
    while n<=length(g)
        if g(n)==0 %0 is -1
            tx=(n-1)*0.1:0.1/100:n*0.1;
            p=(-1)*sin(2*pi*fc*tx);
            plot(tx,p,'LineWidth',1.5);grid on;
            hold on;
        else
            tx=(n-1)*0.1:0.1/100:n*0.1;
            p=(1)*sin(2*pi*fc*tx);
            plot(tx,p,'LineWidth',1.5);grid on;
            hold on;
        end
        n=n+1;
    end
    
%*-*-*-*-*-Modulation QPSK-*-*-*-*-*
    case 4
        axes(handles.axes3)
        hold off;
        g=handles.bits;
        t=0:2*pi/99:2*pi;
        cp=[];sp=[];
        mod=[];mod1=[];
        for n=1:2:9;
            if g(n)==0 & g(n+1)==1;
                die=sqrt(2)/2*ones(1,100);
                die1=-sqrt(2)/2*ones(1,100);
            elseif g(n)==0 & g(n+1)==0;
                die=-sqrt(2)/2*ones(1,100);
                die1=-sqrt(2)/2*ones(1,100);
            elseif g(n)==1 & g(n+1)==0;
                die=-sqrt(2)/2*ones(1,100);
                die1=sqrt(2)/2*ones(1,100);
            elseif g(n)==1 & g(n+1)==1;
                die=sqrt(2)/2*ones(1,100);
                die1=sqrt(2)/2*ones(1,100);
            end
        
            c=cos(t);
            s=sin(t);
            cp=[cp die];    %Amplitude cosino
            sp=[sp die1];   %Amplitude sino
            mod=[mod c];    %cosino carrier (Q)
            mod1=[mod1 s];  %sino carrier   (I)
        end
        bpsk=cp.*mod+sp.*mod1;
        plot(bpsk,'LineWidth',1.5);grid on;
        title('QPSK modulation')
        axis([0 500 -1.5 1.5]); 

%-*-*-*-*Modulation 8PSK*-*-*-*-*-*-*-
    case    5
        axes(handles.axes3)
        hold off;
        g=[handles.bits 0 0];
        t=0:2*pi/149:2*pi;
        cp=[];sp=[];
        mod=[];mod1=[];bit=[];
for n=1:3:length(g);
    if g(n)==0 & g(n+1)==1 & g(n+2)==1
        die=cos(pi/8)*ones(1,150);
        die1=sin(pi/8)*ones(1,150);
        se=[zeros(1,50) ones(1,50) ones(1,50)];
        
    elseif g(n)==0 & g(n+1)==1 & g(n+2)==0
        die=cos(3*pi/8)*ones(1,150);
        die1=sin(3*pi/8)*ones(1,150);
        se=[zeros(1,50) ones(1,50) zeros(1,50)];
        
    elseif g(n)==0 & g(n+1)==0  & g(n+2)==0
        die=cos(5*pi/8)*ones(1,150);
        die1=sin(5*pi/8)*ones(1,150);
        se=[zeros(1,50) zeros(1,50) zeros(1,50)];
        
    elseif g(n)==0 & g(n+1)==0  & g(n+2)==1
        die=cos(7*pi/8)*ones(1,150);
        die1=sin(7*pi/8)*ones(1,150);
        se=[zeros(1,50) zeros(1,50) ones(1,50)];
        
    elseif g(n)==1 & g(n+1)==0  & g(n+2)==1
        die=cos(-7*pi/8)*ones(1,150);
        die1=sin(-7*pi/8)*ones(1,150);
        se=[ones(1,50) zeros(1,50) ones(1,50)];
        
    elseif g(n)==1 & g(n+1)==0  & g(n+2)==0
        die=cos(-5*pi/8)*ones(1,150);
        die1=sin(-5*pi/8)*ones(1,150);
        se=[ones(1,50) zeros(1,50) zeros(1,50)];
        
    elseif g(n)==1 & g(n+1)==1  & g(n+2)==0
        die=cos(-3*pi/8)*ones(1,150);
        die1=sin(-3*pi/8)*ones(1,150);
        se=[ones(1,50) ones(1,50) zeros(1,50)];
        
    elseif g(n)==1 & g(n+1)==1  & g(n+2)==1
        die=cos(-pi/8)*ones(1,150);
        die1=sin(-pi/8)*ones(1,150);
        se=[ones(1,50) ones(1,50) ones(1,50)];
        
    end
    c=cos(t);
    s=sin(t);
    cp=[cp die];    %Amplitude cosino
    sp=[sp -die1];   %Amplitude sino
    mod=[mod c];    %cosino carrier (Q)
    mod1=[mod1 s];  %sino carrier   (I)
end
bpsk=cp.*mod+sp.*mod1;

plot(bpsk,'LineWidth',1.5);grid on;
title('8PSK modulation')
axis([0 500 -1.5 1.5]); 
    case 6
        axes(handles.axes3)
        hold off;
        g=handles.bits;
        fc1=10;
        fc2=50;
        n=1;
    while n<=length(g)
        if g(n)==0 %0 is -1
            tx=(n-1)*0.1:0.1/100:n*0.1;
            p=(1)*sin(2*pi*fc1*tx);
            plot(tx,p,'LineWidth',1.5);grid on;
            hold on;
        else
            tx=(n-1)*0.1:0.1/100:n*0.1;
            p=(1)*sin(2*pi*fc2*tx);
            plot(tx,p,'LineWidth',1.5);grid on;
            hold on;
        end
        n=n+1;
    end


end


guidata(hObject, handles);

%*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
% --- Executes on selection change in select_mod.
function select_mod_Callback(hObject, eventdata, handles)
% hObject    handle to select_mod (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: contents = get(hObject,'String') returns select_mod contents as cell array
%        contents{get(hObject,'Value')} returns selected item from select_mod
%*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
% Read and validate all ten input bits independently.
% The previous ELSEIF chain corrected only the first invalid entry; any
% remaining empty/invalid entries stayed NaN and could later leave 'se'
% undefined in the waveform-generation code.
bitHandles = {handles.bit1, handles.bit2, handles.bit3, handles.bit4, ...
              handles.bit5, handles.bit6, handles.bit7, handles.bit8, ...
              handles.bit9, handles.bit10};

bits = zeros(1,10);
for k = 1:10
    value = str2double(get(bitHandles{k}, 'String'));

    if ~(value == 0 || value == 1)
        choice = questdlg(sprintf('Bit %d must be 0 or 1.', k), ...
                          'Invalid binary value', '1', '0', '1');
        if strcmp(choice, '1')
            value = 1;
        else
            value = 0;
        end
        set(bitHandles{k}, 'String', num2str(value));
    end

    bits(k) = value;
end

handles.bits = bits;
%#######################################
h=handles.bits;
axes(handles.axes1)
hold off;
        bit=[];
        for n=1:2:length(h)-1;
            if h(n)==0 & h(n+1)==1
                se=[zeros(1,50) ones(1,50)];
            elseif h(n)==0 & h(n+1)==0
                se=[zeros(1,50) zeros(1,50)];
            elseif h(n)==1 & h(n+1)==0
                se=[ones(1,50) zeros(1,50)];
            elseif h(n)==1 & h(n+1)==1
                se=[ones(1,50) ones(1,50)];
            end
            bit=[bit se];
        end
        plot(bit,'LineWidth',1.5);grid on;
        axis([0 500 -1.5 1.5]);
%######################################

handles.mod=get(hObject,'Value');
modType=handles.mod;

switch modType
%-*-*-*-*-*-*-*-*-*-Modulation ASK*-*-*-*-*-*-*-*-*-*-*
    case 1
        axes(handles.axes3)
        hold off;
        fc=30;
        g=handles.bits; %modulante
        n=1;
    while n<=length(g)
        if g(n)==0
            tx=(n-1)*0.1:0.1/100:n*0.1;
            p=(1)*sin(2*pi*fc*tx);
            plot(tx,p,'LineWidth',1.5);grid on;
            hold on;
%    axis([0 n*2/fc -3 3]);
        else 
            tx=(n-1)*0.1:0.1/100:n*0.1;
            p=(2)*sin(2*pi*fc*tx);
            plot(tx,p,'LineWidth',1.5);grid on;
            hold on;
        end
            n=n+1;
            
    end
    hold off
%-*-*-*-*-*-*-*-*-*-Modulation OOK*-*-*-*-*-*-*-*-*-
    case 2
        axes(handles.axes3)
        hold off;
        t=0:0.001:1;
        m=1;
        fc=30;
        g=handles.bits; %modulante
        n=1;
        while n<=length(g)
            tx=(n-1)*1/length(g):0.001:n*1/length(g);
            p=(g(n))*sin(2*pi*fc*tx);
            plot(tx,p,'LineWidth',1.5);
            hold on;
            axis([0 (n)*1/length(g) -1.5 1.5]);
            grid on;
            n=n+1;
        end
        hold off

%*-*-*-*-*-*-*Modulation BPSK  -*-*-*-*-*-*-
    case 3
        axes(handles.axes3)
        hold off;
        g=handles.bits;
        fc=10;
        n=1;
    while n<=length(g)
        if g(n)==0 %0 is -1
            tx=(n-1)*0.1:0.1/100:n*0.1;
            p=(-1)*sin(2*pi*fc*tx);
            plot(tx,p,'LineWidth',1.5);grid on;
            hold on;
        else
            tx=(n-1)*0.1:0.1/100:n*0.1;
            p=(1)*sin(2*pi*fc*tx);
            plot(tx,p,'LineWidth',1.5);grid on;
            hold on;
        end
        n=n+1;
    end

%*-*-*-*-*-*-Modulation QPSK*-*-*-*-*
    case 4
        axes(handles.axes3)
        hold off;
        g=handles.bits;
        t=0:2*pi/99:2*pi;
        cp=[];sp=[];
        mod=[];mod1=[];
        for n=1:2:9;
            if g(n)==0 & g(n+1)==1;
                die=sqrt(2)/2*ones(1,100);
                die1=-sqrt(2)/2*ones(1,100);
            elseif g(n)==0 & g(n+1)==0;
                die=-sqrt(2)/2*ones(1,100);
                die1=-sqrt(2)/2*ones(1,100);
            elseif g(n)==1 & g(n+1)==0;
                die=-sqrt(2)/2*ones(1,100);
                die1=sqrt(2)/2*ones(1,100);
            elseif g(n)==1 & g(n+1)==1;
                die=sqrt(2)/2*ones(1,100);
                die1=sqrt(2)/2*ones(1,100);
            end
            c=cos(t);
            s=sin(t);
            cp=[cp die];    %Amplitude cosino
            sp=[sp die1];   %Amplitude sino
            mod=[mod c];    %cosino carrier (Q)
            mod1=[mod1 s];  %sino carrier   (I)
        end
        bpsk=cp.*mod+sp.*mod1;
        plot(bpsk,'LineWidth',1.5);grid on;
        title('QPSK modulation')
        axis([0 500 -1.5 1.5]); 
%*-*-*-*-*-*-*END QPSK-*-*-*-*-*-*-

% *-*-*-*-*-*Modulation 8psk*-*-*-*-*-*-*-
    case    5
        axes(handles.axes3)
        hold off;
        g=[handles.bits 0 0];
        t=0:2*pi/149:2*pi;
        cp=[];sp=[];
        mod=[];mod1=[];bit=[];
for n=1:3:length(g);
    if g(n)==0 & g(n+1)==1 & g(n+2)==1
        die=cos(pi/8)*ones(1,150);
        die1=sin(pi/8)*ones(1,150);
        se=[zeros(1,50) ones(1,50) ones(1,50)];
        
    elseif g(n)==0 & g(n+1)==1 & g(n+2)==0
        die=cos(3*pi/8)*ones(1,150);
        die1=sin(3*pi/8)*ones(1,150);
        se=[zeros(1,50) ones(1,50) zeros(1,50)];
        
    elseif g(n)==0 & g(n+1)==0  & g(n+2)==0
        die=cos(5*pi/8)*ones(1,150);
        die1=sin(5*pi/8)*ones(1,150);
        se=[zeros(1,50) zeros(1,50) zeros(1,50)];
        
    elseif g(n)==0 & g(n+1)==0  & g(n+2)==1
        die=cos(7*pi/8)*ones(1,150);
        die1=sin(7*pi/8)*ones(1,150);
        se=[zeros(1,50) zeros(1,50) ones(1,50)];
        
    elseif g(n)==1 & g(n+1)==0  & g(n+2)==1
        die=cos(-7*pi/8)*ones(1,150);
        die1=sin(-7*pi/8)*ones(1,150);
        se=[ones(1,50) zeros(1,50) ones(1,50)];
        
    elseif g(n)==1 & g(n+1)==0  & g(n+2)==0
        die=cos(-5*pi/8)*ones(1,150);
        die1=sin(-5*pi/8)*ones(1,150);
        se=[ones(1,50) zeros(1,50) zeros(1,50)];
        
    elseif g(n)==1 & g(n+1)==1  & g(n+2)==0
        die=cos(-3*pi/8)*ones(1,150);
        die1=sin(-3*pi/8)*ones(1,150);
        se=[ones(1,50) ones(1,50) zeros(1,50)];
        
    elseif g(n)==1 & g(n+1)==1  & g(n+2)==1
        die=cos(-pi/8)*ones(1,150);
        die1=sin(-pi/8)*ones(1,150);
        se=[ones(1,50) ones(1,50) ones(1,50)];
        
    end
    c=cos(t);
    s=sin(t);
    cp=[cp die];    %Amplitude cosino
    sp=[sp -die1];   %Amplitude sino
    mod=[mod c];    %cosino carrier (Q)
    mod1=[mod1 s];  %sino carrier   (I)
end
bpsk=cp.*mod+sp.*mod1;

plot(bpsk,'LineWidth',1.5);grid on;
title('8PSK modulation')
axis([0 500 -1.5 1.5]); 
    case 6
        axes(handles.axes3)
        hold off;
        g=handles.bits;
        fc1=10;
        fc2=50;
        n=1;
    while n<=length(g)
        if g(n)==0 %0 is -1
            tx=(n-1)*0.1:0.1/100:n*0.1;
            p=(1)*sin(2*pi*fc1*tx);
            plot(tx,p,'LineWidth',1.5);grid on;
            hold on;
        else
            tx=(n-1)*0.1:0.1/100:n*0.1;
            p=(1)*sin(2*pi*fc2*tx);
            plot(tx,p,'LineWidth',1.5);grid on;
            hold on;
        end
        n=n+1;
    end

end %end final


%*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-



% --- Executes during object creation, after setting all properties.
function select_mod_CreateFcn(hObject, eventdata, handles)
% hObject    handle to select_mod (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


